platform :ios, '6.0'

pod 'SBJson', '~> 2.2'

# @see https://github.com/CocoaPods/CocoaPods/issues/1787
post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = 'armv7 armv7s'
    end
  end
end
